apiVersion: v1
kind: Service
metadata:
  name: shippingservice-metrics
  namespace: boutique-support
  labels:
    app: shippingservice
    monitoring: enabled
spec:
  selector:
    app: shippingservice
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  type: LoadBalancer
